### ISSUE TITLE
падает при сложении .brep с телом

### ISSUE THREAD

**Issue by zenbooster** [mirmik/zencad#30]
Так, работает:
```
#!/usr/bin/env python3
#coding: utf-8
from zencad import *

#m = box(10, 10, 10).left(100)
#m += from_brep('./CD21AR-BK.brep')
m = from_brep('./CD21AR-BK.brep')
display(m)
show()
```
а так, нет:
```
#!/usr/bin/env python3
#coding: utf-8
from zencad import *

m = box(10, 10, 10).left(100)
m += from_brep('./CD21AR-BK.brep')
#m = from_brep('./CD21AR-BK.brep')
display(m)
show()
```
[CD21AR-BK.zip](https://github.com/mirmik/zencad/files/3887070/CD21AR-BK.zip)
- кабельный ввод PG21 с сайта производителя, преобразованный в brep с помощью [https://cloud.cadexchanger.com/](url)
При этом с другими моделями других производителей проблем не было.

Косячная модель, или баг в ZenCAD?

**Comment by mirmik** [comment]
Модель как минимум странная. В ней 6422 оболочки по числу граней и 4 пустых твердых тела.
Думаю, модель невалидна.

**Comment by zenbooster** [comment]
Да, попробовал другую модель, всё в порядке.
