### ISSUE TITLE
не запоминает размеры элементов интерфейса при выходе

### ISSUE THREAD

**Issue by zenbooster** [mirmik/zencad#32]
Сабж очень пригодился бы, т.к. каждый раз приходится расставлять всё заново...

**Comment by mirmik** [comment]
Изменение внесено в коммите https://github.com/mirmik/zencad/commit/efd1e042b48b1339badfb7f1b3c7b7bd37a23410.

Теперь при выходе в конфиг сохраняется geometry виджета и положение сплиттеров. 
Добавлен флаг --no-restore для возможности сброса конфигурации.
