### ISSUE TITLE
Грань из svg.path

### ISSUE THREAD

**Issue by hnau256** [mirmik/zencad#34]
Добрый день. Есть потребность импортировать SVG файлы в качестве граней. Библиотека svg.path позволяет извлечь сегменты линии. Но использовать их для построения грани не получается, т.к. необходимы кривые Безье. Можно конечно каким нибудь образом преобразовать SVG к формату, где были бы одни отрезки. Но это не выглядит хорошим решением. Не подскажете ли как данную задачу можно решить?

**Comment by mirmik** [comment]
Добрый день. На настоящий момент в zencad существует инструмент interpolate:
```zencad.interpolate(pnts)```
, который позволяет построит bspline по набору точек. Кривая безье, насколько я припоминаю, частный случай bspline. Так что велика вероятность, что алгоритм interpolate востановит кривую безье, если ему передать узловые точки. 

Запрос хороший. 
Запишем в копилку улучшений. 
- Создание в явном виде кривых безье.
- Создание в явном виде b-spline.
- Экспорт (и позже импорт) svg геометрии. (Строго говоря это уже было когда-то записано)

**Comment by hnau256** [comment]
Да, я видел interpolate, но она же проводит линию через точки, а в svg хранятся ключевые точки  кривой Безье, которые не принадлежат кривой.

**Comment by hnau256** [comment]
Если данный функционал есть в opencascade, то я могу попробовать пробросить его через servose и сделать pullrequest. Правда у меня нет особого опыта в питоне и плюсах, но наверное смог бы по аналогии сделать

**Comment by mirmik** [comment]
Точно.

То-то я думаю, чем тогда interpolate от bspline отличается...

**Comment by hnau256** [comment]
Ок, понял. Попробую поковыряться

**Comment by mirmik** [comment]
Функционал есть. Нам нужен Geom_BezierCurve. 

там работы на десять  минут, сейчас прикину...

**Comment by mirmik** [comment]
Прокинул. Функция 

```
zencad.bezier(pnts)
zencad.bezier(pnts, weights)
```

**Comment by mirmik** [comment]
master ветки репозиториев zencad и servoce обновлены.

**Comment by mirmik** [comment]
Пример использования:

```
#!/usr/bin/env python3

from zencad import *

m = bezier(pnts = [(0,0,0),(1,0,0),(1,1,0)])

disp(m)
show()
```

**Comment by hnau256** [comment]
О, спасибо большое
