### ISSUE TITLE
Как разместить объекты на кривой с шагом?

### ISSUE THREAD

**Issue by zenbooster** [mirmik/zencad#37]
Имеется некоторая кривая полученная с помощью функции interpolate.
Можно ли разместить на этой кривой объекты (в моём случае одинаковые) с некоторым шагом?

**Comment by mirmik** [comment]
На текущий момент такой возможности нет.  
Но в ближайшее время появится. 

Алгоритм работы с длинами параметрических кривых в ядре имеется, так что где-нибудь к завтрашнему вечеру будет.

**Comment by mirmik** [comment]
Ок. Патч запилил, мастер ветку и репозиторий на pypi для линуксовой версии обновил.
В мануал добавлен раздел "Анализ кривых": https://mirmik.github.io/zencad/ru/crvalgo.html

Собственно, метод uniform_points делает равномерную выборку точек из кривой.
Точки могут быть использованы для перемещения объекта:

```
#!/usr/bin/env python3
#coding: utf-8

from zencad import *

icrv=interpolate([
	(0,0,0),
	(10,0,0),
	(0,10,0)
])
pnts=icrv.uniform_points(5)
m=box(1, center=True)

arr = [m.translate(*pnt) for pnt in pnts]

disp(arr)
disp(icrv)
show()
```

![Screenshot 2019-12-19 00:03:27](https://user-images.githubusercontent.com/3998702/71123193-2fbe6d80-21f3-11ea-88ea-b52792590ec2.png)

**Comment by mirmik** [comment]
А... Запрос был о размещении с фиксированным шагом....

**Comment by mirmik** [comment]
```
#!/usr/bin/env python3
#coding: utf-8

from zencad import *

icrv=interpolate([
	(0,0,0),
	(10,0,0),
	(0,10,0)
])

m=box(1, center=True)

arr = [ icrv.linoff_point(3 * i) for i in range(5) ]

for pnt in arr:
	disp(m.translate(*pnt))

disp(icrv)
show()

```

**Comment by mirmik** [comment]
Возможно, будет интересен такой вариант:
```
#!/usr/bin/env python3
#coding: utf-8

from zencad import *

icrv=interpolate([
	(0,0,0),
	(10,0,0),
	(0,10,10)
])

m=box(1, center=True)

arr = [ icrv.d1(icrv.linoff(3*i, 0)) for i in range(8) ]
fromvec = icrv.d1(0)[1]

for pnt, vec in arr:
	s = short_rotate(fromvec=fromvec,tovec=vec)(m)
	disp(s.translate(*pnt))

disp(icrv)
show()
```

![Screenshot 2019-12-19 00:59:26](https://user-images.githubusercontent.com/3998702/71126811-d2c6b580-21fa-11ea-9765-ea91f5b371d1.png)

**Comment by zenbooster** [comment]
Выглядит - то, что надо. Возможно я делаю, что-то не так, но при попытке запустить 1-й пример, в логах появляется следующее:
![изображение](https://user-images.githubusercontent.com/49373256/71243869-53340600-2322-11ea-9d5f-611dc778c633.png)
Версию обновлял, просто запустив:
`python3 -m pip install zencad`
![изображение](https://user-images.githubusercontent.com/49373256/71243802-28e24880-2322-11ea-9242-cd575565a8ee.png)

**Comment by mirmik** [comment]
Обновите пакет pyservoce до версии 1.15.2.

**Comment by zenbooster** [comment]
Уже стоит версия 1.15.2:
![изображение](https://user-images.githubusercontent.com/49373256/71245274-6bf1eb00-2325-11ea-8f31-0ed29ce27e7f.png)

**Comment by mirmik** [comment]
O_o.
Попробуйте сделать из gui: Utility/Invalidate Cache

Если не поможет, то я где-то что-то не то залил.

**Comment by zenbooster** [comment]
Поискал "uniform_points" по репозиторию, нашёл упоминание только в файлах документации.
Сейчас попробую...

**Comment by mirmik** [comment]
А его в zencad и нет. Он линкуется непосредственно из pyservoce.

**Comment by zenbooster** [comment]
> Utility/Invalidate Cache

- это помогло!

**Comment by mirmik** [comment]
В общем-то так и должно было быть. Так и должно было быть. У результата операции interpolate поменялся тип. Он теперь Edge, а не Shape. (Edge наследует от Shape). А из кеша он извлекался со старым типом.
