### ISSUE TITLE
Возможно ли триангулировать и получить массивы треугольников?

### ISSUE THREAD

**Issue by slavust** [mirmik/zencad#38]
Интересно было бы иметь визуализацию в jupyter.

**Comment by mirmik** [comment]
Ну... Технически у нас сейчас есть перевод в stl, но это конечно не позволяет просто получить треугольники в скрипт. Хотя, конечно, всегда можно делать автоматическое создание stl файла с последующим чтением какой-либо питоновской библиотекой, позволяющей работать с stl. 
Нужно посмотреть, какие есть возможности по прямому разложению на треугольники.

Визуализацию в jupiter камрады из cadquery как-то делают, так что это, видимо возможно. Но не всё сразу...

**Comment by mirmik** [comment]
Добавлено.
