### ISSUE TITLE
Interactive objects

### ISSUE THREAD

**Issue by mirmik** [mirmik/zencad#41]
Add interactive object manual creation.

**Comment by oleg-medovikov** [comment]
на счет создания интерактивных линий, можно ли сделать линию не по двум точкам, а по массиву точек? так, например, будет удобно показывать расположение проводов.

**Comment by mirmik** [comment]
Фактически линии из подпакета draw отличаются от геометрических сегментов только тем, что у них есть толщина. Возможно можно просто дать больше свойств при отображении геометрии (надо ядро покурить). И тогда провода можно будет рисовать как интерполяционные линии из геометрического пакета. Потому как тут двойной функционал получается.
