### ISSUE TITLE
Добавить нумерацию строк редакторе

### ISSUE THREAD

**Issue by Amdx12** [mirmik/zencad#43]
Очень не хватает нумерации строк в редакторе. Ошибки выводятся с номером строки, но искать нужную строку затруднительно.

**Comment by mirmik** [comment]
Хорошая мысль. Это полезно.

Использованию встроенного редактора, впрочем, следует предпочесть внешний.

**Comment by Amdx12** [comment]
Я использую Zencad как openscad - как условно-интерактивную рисовалку, сегодня даже распечатал первую деталь, нарисованную полностью в Zencad, в этом случае удобнее все в одном приложении делать. При наличии нумерации строк Zencad стал бы вполне самодостаточным продуктом. Сейчас для отладки приходится открывать файл в PyCharm, а Zencad оставлять только для отрисовки и просмотра консоли.

**Comment by mirmik** [comment]
добавлено в версии 0.28.0
