### ISSUE TITLE
Проблемы с интерфейсом 

### ISSUE THREAD

**Issue by oleg-medovikov** [mirmik/zencad#49]
Почему периодически окно с моделью открывается отдельно? 

![y-02-28_Feb:39:16](https://user-images.githubusercontent.com/57829409/75524463-01dd7c80-5a1f-11ea-911b-a991bf567fdc.png)

**Comment by mirmik** [comment]
Есть такой баг. Причем его не удаётся победить уже довольно долго, вследствии того, что я не до конца понимаю, как вообще работает механизм оконного встраивания. В dev ветке, сейчас довольно большое обновление, там это поведение улучшено, но возможно, пофиксино не до конца.

Оно глаза мозолит, так что рано или поздно я его победю.

**Comment by zenbooster** [comment]
Ещё окно периодически само меняет размер, и его правая граница оказываются за пределами монитора.

**Comment by mirmik** [comment]
По идее с версии 0.29.0 должно работать стабильнее. Мастер ветка и пакет в индексе обновлены.
