### ISSUE TITLE
TypeError: pipe_shell() got an unexpected keyword argument 'spine'

### ISSUE THREAD

**Issue by zenbooster** [mirmik/zencad#63]
Код нормально работает под убунтой после установки по методу:
`python3 -m pip install zencad `
В "PreRelease Windows Standalone version 0.28.1" выдаёт вышеупомянутую ошибку.

**Comment by mirmik** [comment]
Обновить standalone версию пока не получается. 

Поломался pyinstaller по непонятной мне причине.

**Comment by mirmik** [comment]
Закрыто, ибо давно решено.
