### ISSUE TITLE
Solid extrude (question)

### ISSUE THREAD

**Issue by faryna1993** [mirmik/zencad#69]
Добрый день!
у меня есть вопрос.
Могу ли я какими-то образом выполнить команду "extrude" для "solid ", чтобы получить такой же результат как на фото:
![image](https://user-images.githubusercontent.com/11529428/112069843-3d407100-8b75-11eb-9045-f98b5dcb19b2.png)
это два конуса, которые находятся на расстоянии друг от друга и объединены между собой.

Пробовал выполнять бинарные операции в цикле, но это не такой результат, который мне нужен. не могу избавиться от острых углов.
![image](https://user-images.githubusercontent.com/11529428/112070006-8bee0b00-8b75-11eb-9011-fa64c3f6ff20.png)

Вопрос:
Можно ли каким-то образом добиться результата, как на фото 1 ?, нечто вроде команды "extrude ". Или иным вариантом.

Можете мне отправить скрипт с таким примером ?.
Спасибо!

**Comment by faryna1993** [comment]
Дополнения. Хочу для себя сделать симулятор для G-Сode с фрезами.
![image](https://user-images.githubusercontent.com/11529428/112071074-c8bb0180-8b77-11eb-8c48-d7e0de9ea576.png)

**Comment by mirmik** [comment]
Добрый день фот прямо такую поверхность в brep представлении сделать затруднительно, но, учитывая, что она легко дробиться на примитивы, получаем:

```python
#!/usr/bin/env python3
#coding: utf-8

from zencad import *

def wide_cone(r1, r2, h, w):
	halfcone = cone(r1, r2, h) - halfspace().rotateX(deg(90))
	triangle_face = near_face(halfcone, point3(0,0,h/2)) 
	prism = extrude(triangle_face, (0,w,0))
	return prism + halfcone + halfcone.rotZ(deg(180)).movY(w)

disp(wide_cone(10,0,10,20))
show()
```

![Безымянный](https://user-images.githubusercontent.com/3998702/112072540-20129f00-8b83-11eb-9422-4d533e818c80.png)

**Comment by oleg-medovikov** [comment]
А вот мой варик:
![image](https://user-images.githubusercontent.com/57829409/112107944-a9949200-8bc0-11eb-9048-9a2aa2653ede.png)

```
from zencad import *

radius = 30
height = 100
height = 50

o1 = circle(r=radius, angle=math.pi, wire=True).moveY(0.5*height)
o2 = circle(r=radius, angle=-math.pi, wire=True).moveY(-0.5*height)

line1 = sew([ o1, segment(o1.endpoints()[0], o2.endpoints()[-1]),o2 , segment(o2.endpoints()[0], o1.endpoints()[-1]) ] )
fill(line1)
line2 = rectangle(0.1, height, center=True, wire=True).up(height )

list_ = []
list_.append(line1)
list_.append(line2)

m = loft(list_,smooth=False, shell=False, maxdegree=4) 

disp(m)
show()
```

**Comment by faryna1993** [comment]
@mirmik and @oleg-medovikov
### Спасибо за помощь!, и мега быстрый ответ!
