### ISSUE TITLE
GetPosition(obj) and GetSize(obj) (question)

### ISSUE THREAD

**Issue by faryna1993** [mirmik/zencad#70]
Добрый день!
Скажите, каким образом можно получить положение и размеры объекта?

Не смог найти по этому никакой информации.
это что-то должно быть на подобии: GetPosition(obj), GetSize(obj)

**Comment by oleg-medovikov** [comment]
это противоречит логике zencad. вы в скрипте прописываете размеры и позицию, зачем вам получать то, что сами задали? 
а так вводите переменные отвечающие за координаты, выводите их через print

**Comment by faryna1993** [comment]
А, теперь понятно в чем дело. Спасибо!
