### ISSUE TITLE
Отсутствуют scaleX, scaleY etc

### ISSUE THREAD

**Issue by a-baturin** [mirmik/zencad#75]
После какого-то обновления потерялись scale*() функции. scale() просто - на месте.
https://github.com/mirmik/zencad/blob/5717717bdcd549cc21d787c7e81563b0d196d9eb/zencad/geom/transformable.py#L29

В trans.py есть только scale()

**Comment by mirmik** [comment]
Да, действительно. Это технический долг аж с момента перезда на pyocc.  Займусь этим.

**Comment by mirmik** [comment]
Недостаток устранён. Мастер ветка и pypi пакет обновлены.

**Comment by a-baturin** [comment]
Спасибо!
Работает
